### ISSUE TITLE
compilation error db_verbs.cc g++ 7.1.1

### ISSUE THREAD

**Issue by lilmike** [toddsundsted/stunt#20]
Hi,
I just tried compiling stunt's master branch on arch linux, running g++ 7.1.1. I got the following error (I'm including the warning so you can see what function it's in):

db_verbs.cc:167:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (!isdigit(first) || prep >= NPREPS)
db_verbs.cc:172:35: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     if ((ptr = strchr(s, '/')) != '\0')bb db_match_prep(const charefunctioefunctionb_verbs.cc: In  

Any help?
-Michael.

**Comment by tvdijen** [comment]
See if https://github.com/toddsundsted/stunt/pull/19/commits/35f2e3da165a10dea024fd3db7c325192611c6d0 helps you to fix this.. It's a pending pull request.

**Comment by toddsundsted** [comment]
I just merged this PR. Thanks guys!
