### ISSUE TITLE
Creation or deletion of properties on parents of anonymous objects

### ISSUE THREAD

**Issue by jasonhsw** [toddsundsted/stunt#27]
When properties are added or deleted from objects which have anonymous children, those children seem to become "parentless". They lose all properties and verbs.
Adding, programming and deleting verbs doesn't break them, only adding or deleting properties.

**Comment by tvdijen** [comment]
This is documented behaviour...

**Comment by jasonhsw** [comment]
Odd, I just took a look through the docs that I could find, but I didn't find anything about adding/deleting properties breaking anonymous objects.
This is my first time working in a Stunt environment, and I'm working on someone else's MOO, so I hadn't taken a serious look at it before.

**Comment by tvdijen** [comment]
https://groups.google.com/forum/#!searchin/MOO-talk/Stunt$20release%7Csort:date/moo-talk/W0LnRPHDolo/11tb7gMnES4J

**Comment by jasonhsw** [comment]
Ah, I see. Well, I suppose I might as well close this, then. It would be nice if a solution to this problem could be implemented in the future, though.

**Comment by SpiraMirabilis** [comment]
It might be better if they were destroyed instead of being rendered parentless since a valid check is common, but checking parents() is not.

**Comment by tvdijen** [comment]
@SpiraMirabilis Couldn't agree more!

**Comment by toddsundsted** [comment]
those objects shouldn't just be parent-less, they should also be invalid. if that's not the case, that is a bug.
