### ISSUE TITLE
#32.time_zones missing WEST prevents the web interface from working

### ISSUE THREAD

**Issue by raydeejay** [toddsundsted/stunt#3]
The list at #32.time->zones is missing an entry for WEST. This causes the web server to throw this error:

Server Error
#32:format, line 8: Range error

... called from #32:rfc1123_time, line 2
... called from #121:cleanup (this == #142), line 16
(End of traceback)

**Comment by toddsundsted** [comment]
the issue should be opened against [Improvise](https://github.com/toddsundsted/improvise)
